
process.on('unhandledRejection', (err) => {
    console.error(err instanceof Error ? err.message : err);
    process.exit(-1);
});


(async () => {
    try {
        var msg='This convert program will parse a raml to oas. It is work in progress and trying two libraies';
        console.log(msg);
        let wap = require('webapi-parser').WebApiParser;
        let amf = require('amf-client-js');

        //load raml file
        let fs=require('fs')
        let path= require('path')
        let raml = fs.readFileSync(path.resolve(__dirname, 'test.raml'), 'utf8');

        // webapi lib. Working after a fashion
        
        const libModel =  await wap.raml10.parse(raml);
        const yaml = await wap.oas30.generateYamlString(libModel);
        console.log('yaml generated by webapi-parser')
        console.log(yaml);
        //TODO: Save in a file.
        //TODO: Investigate why oas30 lib is generating yaml in oas 2.
        //const apiYaml= await aml.oas30.generateYamlString(apiModel);
        
        // amf lib. 
        //TODO: Investigate Save in a file without suing another lib
        //TODO: Save as Yaml, not JSON without using another lib.
        amf.AMF.init();
        const parser = new amf.Raml10Parser();
        const renderer = new amf.Oas30Renderer()
        const apiModel = await parser.parseStringAsync(raml);
        const apiJson= await renderer.generateString(apiModel);
        console.log('JSON generated by amf-client-js -> webapi parser')
        console.log(apiJson);
        
        process.exit(0);
    } catch(e) {
        throw e;
    }
})();


